---
title: "Primer Parcial"
author: "..."
date: "2024-03-06"
output: 
  html_document:
    df_print: paged
    theme: darkly
    highlight: breezedark
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("readxl", repos = "http://cran.us.r-project.org")
#install.packages("dplyr", repos= "http://cran.us.r-project.org")
#install.packages("ggplot2", repos= "http://cran.us.r-project.org")
#install.packages("descriptr", repos= "http://cran.us.r-project.org")

library(readxl)
library(dplyr)
library(ggplot2)
library(descriptr)
library(dplyr)
library(knitr)

```

## 1. Cargamos el archivo xlsx con la libreria readxl.

```{r}

d_olimpicos <- read_excel("Olimpicos Atenas 2004.xlsx")

set.seed(1234)
ds_olimpicos <- d_olimpicos[sample(1:nrow(d_olimpicos), size=200), ]

```
Eliminamos columnas ID, NOC, Games, Year, Season y City
```{r }
ds_olimpicos$ID <- NULL

ds_olimpicos$NOC <- NULL

ds_olimpicos$Games <- NULL

ds_olimpicos$Year <- NULL

ds_olimpicos$Season <- NULL

ds_olimpicos$City <- NULL

```


## 2.Número total de países participantes por sexo

```{r echo=TRUE, message=FALSE, warning=FALSE}

df_paises_sexo <- ds_olimpicos[, c("Sex", "Team")]

df_paises_sexo_count <- df_paises_sexo %>%
  group_by(Team, Sex) %>%
  summarise(count = n())
df_paises_sexo_count

```



## 3.Medalleria
```{r medallas por paises}

index_con_medalla = ds_olimpicos$Medal != "NA"
m_medalla <- ds_olimpicos[index_con_medalla,]

pais_medalla <- m_medalla[, c("Team", "Medal")]

tabla_Pais_medalla <- table(pais_medalla)
medallas <- as.data.frame.matrix(tabla_Pais_medalla)


medallas$puntos <- (medallas$Bronze + (medallas$Silver * 2) + (medallas$Gold * 3))
medallas_ordenadas <- medallas[order(medallas$puntos, decreasing = TRUE),]
medallas_ordenadas
```



## 4. Diagrama de barras para los deportes en competición

```{r}

df_sports <- ds_olimpicos[, c("Sport")]
df_sports_count <- df_sports %>% 
  group_by(Sport) %>% 
  summarise(count = n())


diag_barra <- ggplot(df_sports_count, mapping=aes(x = Sport, y=count)) +
 geom_col(fill = "#aaaaaa") + 
 labs(
   title = "Deportes en competición",
   x = "",
   y = "Número de participantes") + 
theme_dark() +
theme(
  plot.background = element_rect(fill = "gray20"),
  panel.background = element_rect(fill = "gray20"),
  axis.text = element_text(color = 'white'),
  axis.title = element_text(color = 'white'),
  title = element_text(color = 'white')
)
diag_barra
```

## 5. Diagrama de caja y bigotes para sexo y pesos

```{r message=FALSE, warning=FALSE}
  library(ggplot2)

 
ggplot(data = d_olimpicos, aes(x = Sex, y = Weight)) +
  stat_boxplot(geom = "errorbar", 
               width = 0.2) +
  geom_boxplot(fill = "#88CA7C", colour = "#24693D",  
               alpha = 0.9, outlier.colour = "#5D91BD") +
  scale_y_continuous(name = "Pesos") +    
  scale_x_discrete(name = "Sexo") +       
  ggtitle("Diagrama de caja y bigotes") + 
  theme_dark() +
  theme(
    axis.line = element_line(colour = "black",size = 0.25),
    plot.background = element_rect(fill = "gray20"),
    panel.background = element_rect(fill = "gray20"),
    axis.text = element_text(color = 'white'),
    axis.title = element_text(color = 'white'),
    title = element_text(color = 'white')
)

```

## 6. Resumen completo de altura por sexo
```{r}



df_sexo_altura <- ds_olimpicos[, c("Sex", "Height")]
df_sexo_altura_n <- df_sexo_altura %>%
  group_by(Sex) %>%
  summarise(mean_height = mean(Height),
      median_height = median(Height),
      min_height = min(Height),
      max_height = max(Height),
      mode_height = ds_mode(Height))

df_sexo_altura_n

if (FALSE) {
  
# Generar la tabla con kable
kable(df_sexo_altura_n, 
      caption = "Altura por sexo",
      col.names = c("Sexo", "Media", "Mediana", "Minimo", "Maximo", "Moda"),
      align = "c")
}
```
## 7. Tabla de frecuencias para la altura de las mujeres

```{r  message=FALSE, warning=FALSE}


df_mujer_altura <- ds_olimpicos[, c("Sex", "Height")]
df_mujer_altura <- filter(df_mujer_altura,Sex=="F")

if (FALSE) {
  

df_mujer_altura_n <- df_mujer_altura %>%
  group_by(Sex,Height) %>%
  summarise(count = n())

df_mujer_altura
}

altura_minima <- min(df_mujer_altura$Height)
altura_maxima <- max(df_mujer_altura$Height)

amplitud_intervalo <- 4

intervalos <- seq(altura_minima, altura_maxima, by = amplitud_intervalo)

frecuencia_absoluta <- cut(df_mujer_altura$Height, breaks = intervalos, right = FALSE)

tabla_frecuencia <- table(frecuencia_absoluta)
as.data.frame.array(tabla_frecuencia)

frecuencia_relativa <- prop.table(tabla_frecuencia)


if (FALSE) {
  
ggplot(df_mujer_altura_n, aes(x = Height, y = count)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(title = "Frecuencia de altura por mujer", x = "Altura", y = "Count") +
  theme_minimal()
}

#histograma con frecuencia relativa
ggplot(df_mujer_altura, aes(x = Height)) +
  geom_histogram(aes(y = ..density..), fill = "#aaaaaa", color = "gray20", binwidth = 4) +
  labs(title = "Histograma de Alturas de Mujeres",
       x = "Altura (cm)", y = "Densidad") +
  theme_dark() +
  theme(
  plot.background = element_rect(fill = "gray20"),
  panel.background = element_rect(fill = "gray20"),
  axis.text = element_text(color = 'white'),
  axis.title = element_text(color = 'white'),
  title = element_text(color = 'white')
)

```
